let eResultCode = {
    SUCCESS: 0,
    DB_ERROR: 1,
    NO_DATA_FOUND: 2,
    AUTHENTICATION_FAILED: 3,
    UNAUTHORIZED: 4,
    UNKNOWN: 5,
    INVALID_LOGIN_ID: 6,
    INVALID_PASSWORD: 7,
    SERVICE_ERROR: 8,
    INVALID_REQUEST: 9,
    NOT_FOUND: 10,
    NETWORK_ERRORSERVEERROR: 11,
    CREATED: 12,
    INTERNAL_SERVEERROR: 13,
    UNUSED: 14,
    MULTIPLE_RECORDS: 15,
    BAD_REQUEST: 16,
    R_MAIL_ERROR : 27,
};

export default eResultCode;